name: Unlock-NetEaseMusic

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '37 5 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Cherkout
      uses: actions/checkout@v2

    - name: Install python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Login and unlock
      env:
        EMAIL: ${{secrets.EMAIL}}
        PASSWORD: ${{secrets.PASSWORD}}
        PYTHONIOENCODING: utf-8
        PYTHONLEGACYWINDOWSSTDIO: utf-8
      run: python auto_login.py
